language: cpp

cache:
  directories:
    - cache

env:
  global:
    # Dropbox for comphack/libcomp (DROPBOX_OAUTH_BEARER)
    - secure: "gt2LaFrMpMAFDQr6JHUpnDIY0jZI5neGjDskfeBUo8qZEK5VvyrcaSXJ9I/GvuShAzUAQt+gabD8uzXDjRuMT9v/QIh4dL0ToDRpz9n1K/qrTKUE4mCxwjcj80R75Cei8P2//IuJutYuFIgskrUm1OJ4FcGbOUM1rB40XbhAPB0TFYhnSpvFH78kYzVZpu60RTL1ZvA6Cok3BmJsDj7whoH4OlGxJVNkjCZMj89DF9W9dTlLgKgSY3stLBfEF6GdNA6JTVvNsfEf5Efi1OGZYXuHfONSUUd0peyuyadtH6bu5OrEgM5L+cY4Lo6vdnmwdQdj0uF/oIOJ9zntbZIr91qaY6dRuW9h+UzHoJCymPkyRIemm0eeUJIsoapiw8CorzrgdwwQrzPoSSOPZLUFeghD0UXQA9TOm/TN6QIR6iHzojwCU4AkTDQ5P0EZ8/Y9FBM2i66d2aHfKdkgP64pEjR2mjslsdYUwz2gkNtinckPqYSOqn7ym7D0X1NIoYZW6CHG1KornC+KAszoNVNpnmbddWOYcbwD+tOT5ebsQK1bBHKrlxiJ1mVYdi8KR1IODo0R9cMQEXyX9rJXP31GRVL4lcRZ62JTyBOi1bSeFDHGFTaxewesjrqigVsEMFDnFIDvlq+iYXF5hJCcNwrORoP5M+Bk7UuE1n+VmT+Birw="

jobs:
  include:
    - stage: "Warm cache"
      name: "Warm cache (Linux GCC)"
      os: linux
      compiler: gcc
      env:
        - PLATFORM=gcc5
      script: ci/linux-warmcache.sh

    - stage: "Warm cache"
      name: "Warm cache (Linux Clang)"
      os: linux
      compiler: clang
      env:
        - PLATFORM=clang
      script: ci/linux-warmcache.sh

    - stage: "Warm cache"
      name: "Warm cache (Windows 64-bit)"
      os: windows
      env:
        - PLATFORM=win64
        - QT5_BASE_DIR=C:/Qt/5.12.3/msvc2017_64
      script: ci/windows-warmcache.sh

    - stage: "Build"
      name: "Linux (Clang+Make)"
      os: linux
      dist: trusty
      sudo: required
      compiler: clang
      env:
        - PLATFORM=clang
        - COMPILER_CC=clang
        - COMPILER_CXX=clang++
        - CMAKE_GENERATOR='Unix Makefiles'
      before_install: ci/linux-before_install.sh
      script: ci/linux-libcomp.sh
      deploy:
        provider: releases
        api_key:
          secure: E2hlWRPURFjAKn8d0avdgUiBp1ZE9CoaamqBInqVih87J9JHT6LWhjnyW0y+yIHLdgFpIWYqOgaZ9LzBPzEaZY0AE4jxKBsFV2Zf0R2TKEBdshsrCdANtGZ8PEvqPi8xpwLJbr82dPMcq7hZbgsVUeM/bc4iDdRCg2S2YTzuM9yVAqlnY8cLy5IWHqJR3lGfsXT9ewUXVy8aZmoP2AC8BreXSQou0Z/nqB1s3m7oPTN5c5i3TtYN535mxr9Rcs3tS+vpN2u2c8iyXRjRJjVFf/ZWf4OV3zJyuB+1WBDtsvoFrzRC8u104tp/LZWIX06arUym4OGgBT63Z0nW9QaKiYumAIoU0LhZDshgFUxn1ddrYYvUGoMciN//NwAdvWKHkjvEzkGZgvviYt2GqHP+8SXFXpl1AwSkBN8c30jYFYpJUMQnDfuoquOB3uSn4o6JpjI5hlCm0q4RkY2RBdBFr6uRkddvey4vAVl/Bj93TtkM1zA4/hqoBADoJmzThawiI8npP5CbGAfXN39Q5002DrvwoVFZXJjH0xzw861MCrZV/SeCFMvGgZfHMEGiihXc+80Tx5bmaG0IdE5jbAN77Tr+xNZZHPMv0NrETo7DLCBZQ0fcvR1ZxRXAd0NFgsNISKzUzYgATFjYLz3IFkEUblNIolAYMhrIFOX1a10vGbE=
        skip_cleanup: true
        file_glob: true
        file: libcomp-clang.tar.bz2
        on:
          repo: comphack/libcomp
          branch: develop
          tags: true

    - stage: "Build"
      name: "Linux (Clang+Ninja)"
      os: linux
      dist: trusty
      sudo: required
      compiler: clang
      env:
        - PLATFORM=clang
        - COMPILER_CC=clang
        - COMPILER_CXX=clang++
        - CMAKE_GENERATOR=Ninja
      before_install: ci/linux-before_install.sh
      script: ci/linux-libcomp.sh

    - stage: "Build"
      name: "Linux (GCC5+Make)"
      os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - PLATFORM=gcc5
        - COMPILER_CC=gcc-5
        - COMPILER_CXX=g++-5
        - CMAKE_GENERATOR='Unix Makefiles'
      before_install: ci/linux-before_install.sh
      script: ci/linux-libcomp.sh
      deploy:
        provider: releases
        api_key:
          secure: E2hlWRPURFjAKn8d0avdgUiBp1ZE9CoaamqBInqVih87J9JHT6LWhjnyW0y+yIHLdgFpIWYqOgaZ9LzBPzEaZY0AE4jxKBsFV2Zf0R2TKEBdshsrCdANtGZ8PEvqPi8xpwLJbr82dPMcq7hZbgsVUeM/bc4iDdRCg2S2YTzuM9yVAqlnY8cLy5IWHqJR3lGfsXT9ewUXVy8aZmoP2AC8BreXSQou0Z/nqB1s3m7oPTN5c5i3TtYN535mxr9Rcs3tS+vpN2u2c8iyXRjRJjVFf/ZWf4OV3zJyuB+1WBDtsvoFrzRC8u104tp/LZWIX06arUym4OGgBT63Z0nW9QaKiYumAIoU0LhZDshgFUxn1ddrYYvUGoMciN//NwAdvWKHkjvEzkGZgvviYt2GqHP+8SXFXpl1AwSkBN8c30jYFYpJUMQnDfuoquOB3uSn4o6JpjI5hlCm0q4RkY2RBdBFr6uRkddvey4vAVl/Bj93TtkM1zA4/hqoBADoJmzThawiI8npP5CbGAfXN39Q5002DrvwoVFZXJjH0xzw861MCrZV/SeCFMvGgZfHMEGiihXc+80Tx5bmaG0IdE5jbAN77Tr+xNZZHPMv0NrETo7DLCBZQ0fcvR1ZxRXAd0NFgsNISKzUzYgATFjYLz3IFkEUblNIolAYMhrIFOX1a10vGbE=
        skip_cleanup: true
        file_glob: true
        file: libcomp-gcc5.tar.bz2
        on:
          repo: comphack/libcomp
          branch: develop
          tags: true

    - stage: "Build"
      name: "Windows (VS2017 64-bit)"
      os: windows
      filter_secrets: false
      env:
        - PLATFORM=win64
        - QT5_BASE_DIR=C:/Qt/5.12.3/msvc2017_64
      script: ci/windows-libcomp.sh
      deploy:
        provider: releases
        api_key:
          secure: E2hlWRPURFjAKn8d0avdgUiBp1ZE9CoaamqBInqVih87J9JHT6LWhjnyW0y+yIHLdgFpIWYqOgaZ9LzBPzEaZY0AE4jxKBsFV2Zf0R2TKEBdshsrCdANtGZ8PEvqPi8xpwLJbr82dPMcq7hZbgsVUeM/bc4iDdRCg2S2YTzuM9yVAqlnY8cLy5IWHqJR3lGfsXT9ewUXVy8aZmoP2AC8BreXSQou0Z/nqB1s3m7oPTN5c5i3TtYN535mxr9Rcs3tS+vpN2u2c8iyXRjRJjVFf/ZWf4OV3zJyuB+1WBDtsvoFrzRC8u104tp/LZWIX06arUym4OGgBT63Z0nW9QaKiYumAIoU0LhZDshgFUxn1ddrYYvUGoMciN//NwAdvWKHkjvEzkGZgvviYt2GqHP+8SXFXpl1AwSkBN8c30jYFYpJUMQnDfuoquOB3uSn4o6JpjI5hlCm0q4RkY2RBdBFr6uRkddvey4vAVl/Bj93TtkM1zA4/hqoBADoJmzThawiI8npP5CbGAfXN39Q5002DrvwoVFZXJjH0xzw861MCrZV/SeCFMvGgZfHMEGiihXc+80Tx5bmaG0IdE5jbAN77Tr+xNZZHPMv0NrETo7DLCBZQ0fcvR1ZxRXAd0NFgsNISKzUzYgATFjYLz3IFkEUblNIolAYMhrIFOX1a10vGbE=
        skip_cleanup: true
        file_glob: true
        file: libcomp-win64.zip
        on:
          repo: comphack/libcomp
          branch: develop
          tags: true
